language: java

jdk:
  - oraclejdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test

notifications:
  email:
    on_success: never

sudo: false 

addons:
 
script:
  # other script steps might be done before running the actual SonarQube analysis
